apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svcport
    protocol: TCP
    port: {{ .Values.service.port }} #service port
    targetPort: 3306 # container port