apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: # replicaset labels
    app: frontend
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values deployment.replicas }}
  selector:
    matchLabels: # selector labels
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:{{ .Values.deployment.imageversion }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi