apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-svcport
    protocol: TCP
    port: {{ .Values.service.port }} #service port
    targetPort: 80 # container port