apiVersion: v1
kind: ConfigMap
metadata:
  name: backendconfig
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels: # replicaset labels
    app: backend
    tier: api
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: # selector labels
      app: backend
      tier: api
      project: expense
  template:
    metadata:
      labels:
        app: backend  
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backendconfig