apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-svcport
    protocol: TCP
    port: {{ .Values.service.port }} #service port
    targetPort: 8080 # container port